### ISSUE TITLE
is a standard_name for time required?

### ISSUE THREAD

**Issue by rsignell-usgs** [sci-wms/sci-wms#14]
Will sci-wms require a `standard_name` for time?
https://github.com/ioos/comt/issues/24

**Comment by brianmckenna** [comment]
It should if we're going by [CF-conventions](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#standard-name)

```
desirable to have a more definitive description of the quantity,
which would allow users of data from different sources to determine whether
quantities were in fact comparable
```

Example: handling ROMS' `ocean_time` with corresponding default long_name `long_name: time since initialization` can be solved with internal code to search for known variable names (`ocean_time`), or if a `standard_name: time` field was added to the dataset.

Deferring to a standard approach is much preferable to maintaining a list of known deviations.

Carrying this discussion further, as WMS is spatially based, longitude and latitude should also be required to have standard_name fields, again, to avoid maintaining lists of (`XLONG`, `lon_rho`, `lon`, `long`, etc).

Of course, this touches on an SGRID topic of staggered grids which contain more than a single definitive coordinate system for display.

**Comment by rsignell-usgs** [comment]
Unidata's tools use a much more complex/sophisticated method to determine the time variable:
- find all the variables that are listed in coordinate attributes and add these to a list of possible coordinate variables
- to this list, add variables that have the same name as dimensions
- to this list add variables that have the `axis` attribute, or `positive`.
- check all these variables to see if they have valid units of time, lon, lat, or depth. 
- if these conditions are met for time and the units are valid, then it's a time coordinate variable

I'm not necessarily suggesting that we do this, I'm just pointing out that many of the datasets that currently work with Unidata tools will not work with sci-wms if we insist on the specification of standard_name time.  But of course that would make our software job a lot easier.

**Comment by brianmckenna** [comment]
Complex for sure. A community standard (in it's 6th iteration) and having the originators/owners of a particular dataset specify which variable should be used for this purpose (time) is also sophisticated.

I'm all for the above process. As we all know, it's exceedingly difficult to maintain an expectation all data providers will adhere to the standards. That said, it seems to me, complex methods to find standard dimensions for spatiotemporal datasets fits a [Python CF project](https://github.com/Unidata/netcdf4-python) better than a Python WMS project.

 It's quite similar to how [pyugrid](https://github.com/pyugrid/pyugrid) was used to replace

``` python
    if "nv" in nc.variables:
        #FVCOM
    elif "element" in nc.variables:
        #ADCIRC
    elif "ele" in nc.variables:
        #SELFE
    else:
```

This is part of sci-wms' identity crisis. Are we attempting to robustly, efficiently handle display of specific data, or more generally the handling of any data?

**Comment by kwilcox** [comment]
My vote is "yes".
