### ISSUE TITLE
FYI - installing and testing

### ISSUE THREAD

**Issue by lstillwe** [sci-wms/sci-wms#28]
Just an FYI for the community - @cbcunc @lstillwe going to be trying to install and test the main branch. Hope to provide useful feedback about our experience.

**Comment by cbcunc** [comment]
I have been asked by my management to pose this question: If I install sci-wms from the main branch on any given day, should I expect it to work, at least to the point of serving wms responses for the two registerered datasets CGridTest and UGridTest?

**Comment by ayan-usgs** [comment]
@cbcunc,

I do not think that one should expect the master branch to sci-wms to work for the CGridTest and UGridTest datasets on any given day. The reason for that is new code is periodically merged into the master branch; merges inherently incur some risk that bugs may be introduced into the code repository. Hence, the current master branch will typically have the latest and greatest of the new improvements, but cannot be guaranteed to be working any given time. That said, it's not difficult for developers to tag a stable version of the master branch periodically (think of it as a snapshot of fully working code). One can then install from the tagged version of the master branch rather than the current master branch.

The current tagged version is 0.0.1.

**Comment by rsignell-usgs** [comment]
@ayan-usgs , it looks like you just tagged 0.0.1.   Did you confirm that it works with the test data?

**Comment by ayan-usgs** [comment]
@rsignell-usgs,

Yes, I did confirm that it works with UGridTest and CGridTest.

**Comment by rsignell-usgs** [comment]
Okay, I'm closing this issue then, as the problems @cbcunc is currently having are raised in #29

**Comment by cbcunc** [comment]
Thanks for the great response!
