### ISSUE TITLE
Expressing time values in getCapabilities

### ISSUE THREAD

**Issue by rsignell-usgs** [sci-wms/sci-wms#65]
For our COAWST forecast model, the NcWMS getCaps 
http://geoport.whoi.edu/thredds/wms/coawst_4/use/fmrc/coawst_4_use_best.ncd?service=WMS&version=1.3.0&request=GetCapabilities
show times like this:

```
<Dimension name="time" units="ISO8601" multipleValues="true" current="true" default="2015-07-30T14:00:00.000Z">
2012-06-25T01:00:00.000Z/2012-06-26T00:00:00.000Z/PT1H,2012-06-27T01:00:00.000Z/2012-06-30T00:00:00.000Z/PT1H,2012-07-02T01:00:00.000Z/2012-07-03T00:00:00.000Z/PT1H,2012-07-05T01:00:00.000Z/2012-07-09T00:00:00.000Z/PT1H,2012-07-10T01:00:00.000Z/2012-07-14T00:00:00.000Z/PT1H,2012-07-17T01:00:00.000Z/2012-07-18T00:00:00.000Z/PT1H,2012-07-19T01:00:00.000Z/2012-08-14T00:00:00.000Z/PT1H,
...
</Dimension>
```

while the sci-wms getCaps:
http://sci-wms.whoi.edu/wms/datasets/coawst?REQUEST=GetCapabilities
doesn't seem to show any intervals, and shows only an extent:

```
<Dimension name="time" units="ISO8601" />
<Extent name="time">2012-06-25T01:00:00Z/2015-07-31T00:00:00Z</Extent>
```

Should we be including the intervals, just as ncWMS is doing?

```


```

**Comment by kwilcox** [comment]
Your link is to a WMS 1.3.0 GetCaps, the `sci-wms` is WMS 1.1.1 only.

**Comment by rsignell-usgs** [comment]
Umm, okay, but the ncWMS WMS 1.1.1 getcaps 
http://geoport.whoi.edu/thredds/wms/coawst_4/use/fmrc/coawst_4_use_best.ncd?service=WMS&version=1.1.1&request=GetCapabilities
has intervals specified also:

```
<Extent name="time" multipleValues="1" current="1" default="2015-07-31T00:00:00.000Z">
      2012-06-25T01:00:00.000Z/2012-06-26T00:00:00.000Z/PT1H,
      2012-06-27T01:00:00.000Z/2012-06-30T00:00:00.000Z/PT1H,
      2012-07-02T01:00:00.000Z/2012-07-03T00:00:00.000Z/PT1H,
      2012-07-05T01:00:00.000Z/2012-07-09T00:00:00.000Z/PT1H,
      ...
</Extent>
```

**Comment by kwilcox** [comment]
@rsignell-usgs Hmm I probably should have checked the 1.1.1 server as well!

I've never ever seen this behavior before.  Does the dataset have a non-uniform time resolution?  I wrote the code in ncWMS to return time intervals instead of listing every individual time and don't remember supporting non-uniform resolutions like this appears to do... maybe some additions have been made since then (a long time ago). Either way, I don't necessarily love this, but don't hate it either! It could easily be supported in sci-wms since we cache the time variable locally (as does ncWMS).

@ayan-usgs @acrosby @brianmckenna @shane-axiom @cgalvarino Any thoughts on this? :+1: or :-1:? Would mostly affect clients who read the GetCaps... I'm not sure what the support is like for this type of return in the current client implementations outside of Godiva2.

**Comment by brianmckenna** [comment]
:+1:  I'd like to see it supported, seems useful for some of the models which may not have continuous time coverage like every other day as indicated above. I used [isodate](https://pypi.python.org/pypi/isodate) a while back for duration and didn't have any issues from the Python side of things.

GFS would be another example, has non-uniform output times. 3 hour output to 10 days, 12 hour output day 10-16, could be informative there.

**Comment by ayan-usgs** [comment]
:+1:  I'd like to see non-uniform time resolutions supported as well.

**Comment by cgalvarino** [comment]
I think I'd be a fan.  This might help cover up another one of sci-wms's warts . . . er . . . features:  requesting a whack time completely out of bounds, yet an image is returned to you.  A completely ambiguous image.  If @rsignell-usgs makes a GetMap request for TIME=20200101T0000Z, I bet he gets back an image.  Knowing what times are truly available might help us wee clients prevent a user from making such a request.

**Comment by ayan-usgs** [comment]
It would also make it more evident in the getCaps if variables are using different time variables. This tends to happen if there's more than one variable with `standard_name=time`. It might help prevent instances where a user might be looking at two different variables at what is believed to be the same time, but isn't.

**Comment by acrosby** [comment]
I'd be inclined to keep the "nearest" functionality because time has a funny way of getting messed up due to precision...but with that said I think supporting a more descriptive definition of what's available within the GetCaps would be beneficial--particularly, if we can get clients to support the definitions fully.

**Comment by kwilcox** [comment]
https://github.com/sci-wms/sci-wms/pull/68
