### ISSUE TITLE
Subset before data access

### ISSUE THREAD

**Issue by ayan-usgs** [sci-wms/sci-wms#79]
The entire offset grid is extracted every request from the raw dataset. Instead, it should be subsetted to lighten the load over the wire.

Example here: https://github.com/ayan-usgs/sci-wms/blob/eb01185ff9f0d56ac1a35b43670ef3bf948250aa/wms/models/datasets/sgrid.py#L154-L175

**Comment by ayan-usgs** [comment]
Issue first brought up in PR #75.

**Comment by kwilcox** [comment]
I'm not sure the benefits of faster data extraction outweigh the negatives: inconsistent colorscale between autoscaled tiles.

UGRID requests an entire 2D slice at a time and elevation before drawing.  Why?  Because to correctly auto-scale tiled request, the min/max of the layer needs to be computed on the entire 2D grid, not the individual tile data. If the individual tile data was used to compute the min/max, the tiles would all end up with different color scales. In sc-wms/ncWMS aware clients, this can be easily solved using the `COLORSCALERANGE` parameter, but clients such as TerraJS that don't know about this extra parameter, sci-wms layers will look terrible when tiled.

**Comment by ocefpaf** [comment]
@kwilcox I am completely ignorant on WMS details and implementations, but would reading the the `min`, `max` netCDF attribute for each variable help?  It is usually unavailable, but that can be fixed with `ncml`, right @rsignell-usgs?

**Comment by rsignell-usgs** [comment]
We _will_ implement the COLORSCALERANGE in terriaJS.   Setting color range defaults (whether on the server, in the file, or in NCML) only gives you an initial map that doesn't look foolish, but to really be of use, we need to have the user control COLORSCALE range (and NUMCONTOURS) from the application.

**Comment by kwilcox** [comment]
Sounds like we should go ahead with implementing the "subset before data access" paths for sgrid and ugrid and let the user/clients figure out the "ugly tiles" issue!

One of these things will needs to happen for clients to work correctly:

1.) Client need to support COLORSCALERANGE
2.) sci-wms admin needs to manually set min/max for the variables on the dataset page (ie. http://sci-wms.whoi.edu/wms/datasets/coawst/show - if you are logged in as an admin you can change the values). @ocefpaf These **are** auto-populated with the `valid_range` or  `valid_min` and `valid_max` parameters if they exists on a variable: https://github.com/sci-wms/sci-wms/blob/master/wms/models/datasets/netcdf.py#L196-L203.

**Comment by ocefpaf** [comment]
> These are auto-populated.

Cool!  So there is no reason to read all the data before hand.  If someone gets an ugly tile they can fix it manually or fix the dataset.

**Comment by rsignell-usgs** [comment]
Isn't it true that for unstructured grid data, there is really no good way to efficiently subset the data anyway?  
The best approach is read all the data, then repackage just the indices that make up the subset into a new array.   If you try to pull array elements one-by-one that make up the subset, it will be much slower. 

No?

**Comment by rsignell-usgs** [comment]
On the subject of using `valid_range` to set the color limits, I guess that's better than nothing, but these are really designed to be the range that no value could possibly be outside.  Because if it _is_ outside, it will be treated as bad/missing and set to the `_FillValue`, per CF Conventions. 

So we usually don't set `valid_range`, we just set bad/missing values to `_FillValue`. 

In CF 1.7, there is a new `actual_range` parameter, but that's not really what we want either, because that is supposed to be calculated over the actual range of the data. 

For salinity, the minimum value of the `actual_range` is often 0.0 (if we have rivers around), but we want to plot our coastal salinity data with something like 28-32 as the minimum value. 

What I'm really saying here is that we should have another attribute called `color_range` or `scale_range` or `plot_range` that we use for this purpose. 

I thought this was discussed on the CF or ncWMS mailing lists a while back, and that maybe attribute names were suggested for this purpose, but I could not find it. 

And whatever we pick, as I said before, these default color ranges only will give us initial maps that don't look stupid, not that it will be sufficient (in general) to allow users to effectively browse the data.

**Comment by rsignell-usgs** [comment]
Okay, that was too long, so nobody read it. 

Let me try this way. 

Please vote:
a. `color_range`
b. `scale_range`
c. `plot_range`
d.  None of the above

**Comment by kwilcox** [comment]
Reminiscent of this: https://github.com/USGS-CMG/usgs-cmg-portal/issues/75

**Comment by kwilcox** [comment]
The IOOS Glider DAC uses `colorBarMinimum` and `colorBarMaximum`: http://data.ioos.us/gliders/erddap/info/ru01-20140123T1250/index.html.  This might be from the Glider DAC NetCDF spec or something they manually add. @lukecampbell, do you add those attribute manually?

**Comment by ocefpaf** [comment]
I don't think I am qualified to vote but, even thought I don't like `colorBar{Minimum,Maximum}`, I vote for consistency.

**Comment by lukecampbell** [comment]
The attributes that @kwilcox are referring to are added to the ERDDAP catalog in our ingesting of new datasets for GliderDAC.
https://github.com/ioos/ioosngdac/blob/master/erddap/templates/private/dataset.deployment.xml#L89-L93

**Comment by kwilcox** [comment]
@rsignell-usgs I'm voting for a combination of `scale_range`, `scale_min`, `scale_max`, and `scale_type`.  `scale_type` can be assumed `linear` if left out.  This should make it into `CF 2.0`!

```
float chlorophyll(t, z, y, x);
        chlorophyll:scale_range = 0.001f, 500.0f;
        chlorophyll:scale_type = 'log';
```

```
float chlorophyll(t, z, y, x);
        chlorophyll:scale_min = 0.001f;
        chlorophyll:scale_max = 500.0f;
        chlorophyll:scale_type = 'log';
```

```
float air_temp(t, z, y, x);
        air_temp:scale_range = -50.0f, 100.0f;
        air_temp:scale_type = 'linear';
```

```
float air_temp(t, z, y, x);
        air_temp:scale_min = -50.0f;
        air_temp:scale_max = 100.0f;
        air_temp:scale_type = 'linear';
```
