### ISSUE TITLE
Error Loading Layer: Invalid ISO 8601 date

### ISSUE THREAD

**Issue by metanomy** [sci-wms/sci-wms#80]
Posting mostly for awareness while I investigate further.
- sci-wms configured with wfs fvcom: (http://tampabaymap.org:7002/wms/datasets/wfsfvcomagg?REQUEST=GetCapabilities)
- TerriaJS-based web-app (tampabaymap.org) configured to display "u" layer from sci-wms:
                      {
                          "name": "WFS FVCOM",
                          "type": "wms",
                          "url": "http://tampabaymap.org/sci-wms/wms/datasets/wfsfvcomagg",
                          "layers": "u",
                          "legendUrl" : "http://ocgweb.marine.usf.edu/usf_logo_sm.jpg"
                      }

Attempting to load the layer causes the error.

**Comment by kwilcox** [comment]
Can you include the actual GetMap request that the JS client is sending?

**Comment by metanomy** [comment]
I see where gunicorn_config_prod.py defines an access log (gunicorn_access.log) but can't actually seem to find that log file in /srv/sci-wms/logs. Any suggestions?

I think the error might be in the GetCapabilities request that TerriaJS requests first before the GetMap. Here's the URL being generated for that: http://tampabaymap.org/sci-wms/wms/datasets/wfsfvcomagg?service=WMS&version=1.3.0&request=GetCapabilities

**Comment by kwilcox** [comment]
This seems to be an issue with the GetCapabilties using ISO8601 period syntax (start/end/period) instead of listing out the individual timestamps for each available model step.  Without knowing more about how TerriaJS parses WMS GetCaps I don't really have a good answer. If you can find the JS code and post a link here I'll take a quick look.

The WMS spec allows ISO8601 periods:

```
EXAMPLE:
Here is a <Layer> element with Extents specified in WMS Capabilities XML ('...'
indicates XML omitted for clarity):
<Layer>
<!-- Declare dimensions in use. Declarations are inherited by enclosed Layers. -->
<Dimension name="time" units="ISO8601" />
<Dimension name="temperature" units="Kelvin" unitSymbol="K" />
<Dimension name="elevation" units="EPSG:5030" />
…
<Layer> …
<!-- Specify extent of Layer. Extents are inherited by enclosed Layers. -->
<Extent name="time" default="2000-10-17">1996-01-01/2000-10-17/P1D</Extent>
<Extent name="elevation" default="0">0/10000/100</Extent>
<Extent name="temperature" default="300">230,300,400</Extent>
</Layer>
…
</Layer>
```

Table C.1  Syntax for Listing One or More Dimensional Values

| Syntax | Meaning |
| --- | --- |
| value | A single value |
| value1,value2,value3,... | A list of multiple values |
| min/max/resolution | An interval defined by its lower and upper bounds and its resolution. |
| min1/max1/res1,min2/max2/res2,... | A list of multiple intervals |

**Comment by metanomy** [comment]
I think the TerriaJS WMS GetCaps is built from this module: https://github.com/TerriaJS/terriajs/blob/master/lib/Models/WebMapServiceCatalogItem.js

**Comment by rsignell-usgs** [comment]
Yeah, it looks like the code here
https://github.com/TerriaJS/terriajs/blob/master/lib/Models/WebMapServiceCatalogItem.js#L527-L541
just expects a list of times.

**Comment by rsignell-usgs** [comment]
@kwilcox would you be able to submit a PR for this?

**Comment by rsignell-usgs** [comment]
Well, I guess we should just ping the TerriaJS guys first.   I could do that.

**Comment by metanomy** [comment]
Bounty added: https://www.bountysource.com/issues/27033178-handle-wms-time-inverval-specification

**Comment by kwilcox** [comment]
this is fixed in TerriaJS!
